### ISSUE TITLE
Registration page passport upload button not visible

### ISSUE THREAD

**Issue by gjbeattie** [sonicpanther101/school-website#2]
The passport upload button could not be seen on the registration page until I scrolled down on the central registration screen. I was not obvious that I could scroll down.

**Comment by sonicpanther101** [comment]
Fixed for all resolutions I tested, should be fixed for every resolution.

From: `<Card className="w-[90%] lg:w-[40%] mx-[5%] lg:mx-[30%] my-[20%] lg:my-[10%] h-[85vh] lg:h-[70vh] flex flex-col">`
To: `<Card className="w-[90%] lg:w-[40%] mx-[5%] lg:mx-[30%] my-[20%] lg:my-[10%] h-[115vh] lg:h-[85vh] flex flex-col">` 

[Commit where change was made](https://github.com/sonicpanther101/school-website/commit/0bf1e906e7eadfe108428dd75aa6bc6cfb41c6bb)
